# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 13:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodlist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='n_portions',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dish',
            name='time',
            field=models.IntegerField(default=0),
        ),
    ]
