# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-19 13:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0005_auto_20170319_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='friend_profiles', to=settings.AUTH_USER_MODEL),
        ),
    ]
